import type { RuntimeConfig } from './runtime-config'

export function camelToUpperSnake(key: string): string {
  return key
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
    .toUpperCase()
}

function generateType(value: unknown, indent: number): string {
  const pad = '  '.repeat(indent)
  if (value === null || value === undefined) return 'unknown'
  if (typeof value === 'string') return 'string'
  if (typeof value === 'number') return 'number'
  if (typeof value === 'boolean') return 'boolean'
  if (typeof value === 'object' && !Array.isArray(value)) {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return 'Record<string, unknown>'
    const lines = entries.map(([key, val]) => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`
      return `${pad}  ${safeKey}: ${generateType(val, indent + 1)}`
    })
    return `{\n${lines.join('\n')}\n${pad}}`
  }
  return 'unknown'
}

export function generateRuntimeConfigTypes(runtimeConfig: RuntimeConfig): string {
  const publicType = generateType(runtimeConfig.public, 0)
  const serverEntries = Object.entries(runtimeConfig).filter(([key]) => key !== 'public')
  const serverType = serverEntries.length === 0
    ? 'Record<string, unknown>'
    : `{\n${serverEntries.map(([key, value]) => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`
      return `  ${safeKey}: ${generateType(value, 1)}`
    }).join('\n')}\n}`

  return `// Generated by nuxe
export interface RuntimeConfig {
${serverEntries.length === 0 ? '  [key: string]: unknown' : serverEntries.map(([key]) => {
  const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`
  return `  ${safeKey}: ${generateType(runtimeConfig[key], 1)}`
}).join('\n')}
  public: ${publicType}
}

declare module '@dvlkit/nuxe' {
  export function useRuntimeConfig(): RuntimeConfig
}

declare module '@dvlkit/nuxe/runtime' {
  export function useRuntimeConfig(): RuntimeConfig
}
`
}
