import { describe, expect, it } from 'vitest'
import {
  generateClientMiddlewaresModule,
  generateServerMiddlewaresModule,
} from '../../lib/middleware/codegen'
import type { ScannedMiddleware } from '../../lib/middleware/scanner'

function mw(name: string, opts: { global?: boolean; serverOnly?: boolean } = {}): ScannedMiddleware {
  return {
    name,
    path: `/abs/path/to/${name}.ts`,
    global: opts.global ?? false,
    serverOnly: opts.serverOnly ?? false,
  }
}

describe('generateClientMiddlewaresModule', () => {
  it('returns empty module for empty input', () => {
    const code = generateClientMiddlewaresModule([])
    expect(code).toContain('export const middlewares = {}')
    expect(code).toContain('export const globalMiddlewares = []')
  })

  it('emits named entries only', () => {
    const code = generateClientMiddlewaresModule([mw('admin')])
    expect(code).toContain('export const middlewares = {')
    expect(code).toContain('"admin": __mw_0')
    expect(code).toContain('export const globalMiddlewares = []')
  })

  it('emits globals as an array', () => {
    const code = generateClientMiddlewaresModule([mw('auth', { global: true })])
    expect(code).toContain('export const globalMiddlewares = [__mw_0]')
  })

  it('excludes server-only middleware', () => {
    const code = generateClientMiddlewaresModule([
      mw('auth', { global: true }),
      mw('admin'),
      mw('premium', { serverOnly: true }),
    ])
    expect(code).toContain('import __mw_0 from "/abs/path/to/auth.ts"')
    expect(code).toContain('import __mw_1 from "/abs/path/to/admin.ts"')
    expect(code).not.toContain('premium')
    expect(code).not.toContain('/abs/path/to/premium.ts')
  })

  it('emits imports with JSON-stringified absolute paths', () => {
    const code = generateClientMiddlewaresModule([mw('admin')])
    expect(code).toContain('import __mw_0 from "/abs/path/to/admin.ts"')
  })

  it('includes auto-generated banner', () => {
    const code = generateClientMiddlewaresModule([mw('admin')])
    expect(code).toContain('// AUTO-GENERATED by nuxe')
  })
})

describe('generateServerMiddlewaresModule', () => {
  it('returns empty module for empty input', () => {
    const code = generateServerMiddlewaresModule([])
    expect(code).toContain('export const middlewares = {}')
    expect(code).toContain('export const globalMiddlewares = []')
  })

  it('includes server-only middleware', () => {
    const code = generateServerMiddlewaresModule([
      mw('auth', { global: true }),
      mw('premium', { serverOnly: true }),
      mw('audit', { global: true, serverOnly: true }),
    ])
    expect(code).toContain('/abs/path/to/auth.ts')
    expect(code).toContain('/abs/path/to/premium.ts')
    expect(code).toContain('/abs/path/to/audit.ts')
  })

  it('emits globals including server-only ones', () => {
    const code = generateServerMiddlewaresModule([
      mw('auth', { global: true }),
      mw('audit', { global: true, serverOnly: true }),
    ])
    expect(code).toContain('export const globalMiddlewares = [__mw_0, __mw_1]')
  })

  it('emits named map including server-only ones', () => {
    const code = generateServerMiddlewaresModule([
      mw('admin'),
      mw('premium', { serverOnly: true }),
    ])
    expect(code).toContain('"admin": __mw_0')
    expect(code).toContain('"premium": __mw_1')
  })
})

describe('client vs server parity', () => {
  const allMiddlewares = [
    mw('auth', { global: true }),
    mw('admin'),
    mw('premium', { serverOnly: true }),
    mw('audit', { global: true, serverOnly: true }),
  ]

  it('client excludes server-only entries', () => {
    const client = generateClientMiddlewaresModule(allMiddlewares)
    expect(client).not.toContain('premium')
    expect(client).not.toContain('audit')
  })

  it('server includes all entries', () => {
    const server = generateServerMiddlewaresModule(allMiddlewares)
    expect(server).toContain('admin')
    expect(server).toContain('premium')
    expect(server).toContain('audit')
  })

  it('client module is a strict subset of server module (in imports)', () => {
    const client = generateClientMiddlewaresModule(allMiddlewares)
    const server = generateServerMiddlewaresModule(allMiddlewares)

    const clientImports = client.match(/import __mw_\d+ from ".*?"/g) ?? []
    const serverImports = server.match(/import __mw_\d+ from ".*?"/g) ?? []

    expect(clientImports.length).toBeLessThan(serverImports.length)
    for (const line of clientImports) {
      expect(serverImports).toContain(line)
    }
  })
})
