import type { ScannedPlugin } from './scanner'

export function generateClientPluginsModule(plugins: ScannedPlugin[]): string {
  return generateModule(plugins.filter(p => p.mode !== 'server'))
}

export function generateServerPluginsModule(plugins: ScannedPlugin[]): string {
  return generateModule(plugins.filter(p => p.mode !== 'client'))
}

function generateModule(plugins: ScannedPlugin[]): string {
  if (plugins.length === 0) {
    return 'export const plugins = []\n'
  }

  const imports = plugins
    .map((p, i) => `import __plugin_${i} from ${JSON.stringify(p.path)}`)
    .join('\n')

  const exports = plugins
    .map((_, i) => `  __plugin_${i}`)
    .join(',\n')

  return [
    '// AUTO-GENERATED by nuxe - do not edit',
    imports,
    '',
    `export const plugins = [\n${exports}\n]`,
    '',
  ].join('\n')
}
