import type { ScannedMiddleware } from './scanner'

export function generateMiddlewaresModule(middlewares: ScannedMiddleware[]): string {
  if (middlewares.length === 0) {
    return [
      'export const middlewares: {}',
      'export const globalMiddlewares = []',
      '',
    ].join('\n')
  }

  const indexOf = (m: ScannedMiddleware) => middlewares.indexOf(m)
  const importLines = middlewares
    .map((m, i) => `import __mw_${i} from ${JSON.stringify(m.path)}`)
    .join('\n')

  const namedEntries = middlewares
    .filter(m => !m.global)
    .map(m => `  ${JSON.stringify(m.name)}: __mw_${indexOf(m)}`)
    .join(',\n')

  const globalEntries = middlewares
    .filter(m => m.global)
    .map(m => `  __mw_${indexOf(m)}`)
    .join(', ')

  return [
    '// AUTO-GENERATED by nuxe - do not edit',
    importLines,
    '',
    `export const middlewares = {\n${namedEntries}\n}`,
    `export const globalMiddlewares = [${globalEntries}]`,
    '',
  ].join('\n')
}
